import Head from "next/head";
import { NicaraguaDashboardLayout } from "../../components/Dashboard/NicaraguaDataLayout";
import styles from "../../styles/Home.module.css";

export default function NicaraguaData() {
  return (
    <div className={styles.container}>
      <Head>
        <title>COVID-19 Nicaragua</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NicaraguaDashboardLayout />
    </div>
  );
}
